# Generated by Django 3.2.3 on 2021-11-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
