# Generated by Django 3.2.3 on 2021-11-21 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceview',
            name='hate_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='hate_ceviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ceview',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_ceviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='hate_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='hate_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
