# Generated by Django 3.2.3 on 2021-11-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceview',
            name='rank',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
