# Generated by Django 3.2.3 on 2021-11-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceview',
            name='rank',
        ),
    ]
