# Generated by Django 3.2.3 on 2021-11-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='image',
        ),
    ]
