# Generated by Django 3.2.3 on 2021-11-21 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_remove_movie_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='hate_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='hate_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
